Add a sidecli subcommand to
marigold-dev/sidechain pull request #82
Opened 2021-07-28 04:29 UTC by anchpop

# Depends

Depends on #72 and #81 

# Problem

See #73. Some files are needed to set up a node, a convenient command should be available to generate all of them. 

# Solution

This adds a `setup-node` command to sidecli that takes the information needed to set up a node, and a folder, and creates the appropriate files inside that folder.

# Draft

Things to do before this is ready to merge

- [ ] Test it locally. I can't test it right now because I don't know what specific values should be used, e.g. for the node's EDSK_SECRET_KEY.
- [ ] Figure out whether we should be creating the validators files
- [ ] Figure out whether we should create the folder, or require that it exist but be empty (currently we do neither, just requiring the folder already exists)

2021-07-28 22:14 UTC, EduardoRFS commented
The validators should be empty for now, and you can try the creation with any `edsk`.

I would vote for creating the folder automatically.

2021-07-28 22:18 UTC, anchpop commented on bin/sidecli.re
> +  // If not, should we check that the provided folder is empty?
We should probably create the folder if it's not present and error otherwise

2021-07-28 22:18 UTC, anchpop commented on bin/sidecli.re
> +  // let _validators = assert(false); // TODO: create validators file. I think this requires peer discovery?
We can just create an empty validators file for now

2021-07-29 20:36 UTC, EduardoRFS requested changes

2021-07-29 20:36 UTC, EduardoRFS commented on bin/sidecli.re
> +      secret: secret',
this should be `tezos_secret`

2021-07-29 20:36 UTC, EduardoRFS commented on bin/sidecli.re
> +      required_confirmations: 30 // TODO: What value to use here? I think Tezos finality is 30 blocks
https://github.com/marigold-dev/sidechain/issues/73#issue-954177362

I mentioned here, `required_confirmations` should be 10 out of the box

2021-07-30 01:02 UTC, EduardoRFS approved these changes
I personally don't like the code as it needs some refactoring, but it's okay to merge by now just need an issue for the additional task that requires `mkdirp`

![anime girl confused when approving code that could be improved](https://user-images.githubusercontent.com/3393115/127584181-777e7565-bd02-40ae-a7ec-0dd01c56e262.gif)
.

2021-07-30 13:13 UTC, anchpop commented on bin/sidecli.re
> +      required & pos(1, some(edsk_secret_key), None) & info([], ~doc, ~docv)
I'm happy to fix it, do you know of a way to create a named required argument? I thought optional arguments could be given names but required ones couldn't - I could just return the error myself if any of the optional arguments aren't given, I'll do that if there's no better way.

2021-07-30 13:58 UTC, callistonianembrace approved these changes

2021-07-30 16:50 UTC, EduardoRFS commented on bin/sidecli.re
> +      required & pos(1, some(edsk_secret_key), None) & info([], ~doc, ~docv)
This seems to work to me ```ocaml

2021-07-30 17:04 UTC, anchpop commented on bin/sidecli.re
> +      required & pos(1, some(edsk_secret_key), None) & info([], ~doc, ~docv)
That worked, thanks!

2021-07-31 00:47 UTC, merged